species: # specify species code 

snvs_annotation: # specify snvs annotation file location

genes_annotation: # specify genes annotation file location

protein_db: # specify translated protein seuquence fasta file location 

afdb_diamond_db: # specify afdb diamond database file location

esm_diamond_db: # specify esm database file location
